name: Generate Space Shooter Graph

on:
  schedule: # Runs every 24 hours
    - cron: "0 0 * * *" 
  workflow_dispatch: # Allows you to run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Space Shooter
        uses: actions/checkout@v4
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/space-shooter-graph.svg
            dist/space-shooter-graph-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
