name: Generate Space Shooter Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

  jobs:
  update-game:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: czl9707/gh-space-shooter@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          outputs: |
            dist/space-shooter-graph.svg
            dist/space-shooter-graph-dark.svg?palette=github-dark
          strategy: 'random'

